//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QuanLySinhVien.WebServiceDemo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback myCloseOperationCompleted;
        
        private System.Threading.SendOrPostCallback myconnectOperationCompleted;
        
        private System.Threading.SendOrPostCallback taobangOperationCompleted;
        
        private System.Threading.SendOrPostCallback SinhVien_ThemOperationCompleted;
        
        private System.Threading.SendOrPostCallback SinhVien_XoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SinhVien_SuaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaoBangKhoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Khoa_ThemOperationCompleted;
        
        private System.Threading.SendOrPostCallback Khoa_SuaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Khoa_XoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaoBangMonHocOperationCompleted;
        
        private System.Threading.SendOrPostCallback MonHoc_ThemOperationCompleted;
        
        private System.Threading.SendOrPostCallback MonHoc_SuaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MonHoc_XoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaoBangKQOperationCompleted;
        
        private System.Threading.SendOrPostCallback KetQua_ThemOperationCompleted;
        
        private System.Threading.SendOrPostCallback KetQua_SuaOperationCompleted;
        
        private System.Threading.SendOrPostCallback KetQua_XoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaoBangTKMonHocOperationCompleted;
        
        private System.Threading.SendOrPostCallback MONHOC_TimTheoMaMHOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaoBangTKKhoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Khoa_TimTheoMaKhoaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaoBangTKLanThiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KetQua_TimTheoLanThiOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimKiem_ThongTinSVOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimKiem_ThongTinSVGridViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimKiem_DiemTrungBinhOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::QuanLySinhVien.Properties.Settings.Default.QuanLySinhVien_WebServiceDemo_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event myCloseCompletedEventHandler myCloseCompleted;
        
        /// <remarks/>
        public event myconnectCompletedEventHandler myconnectCompleted;
        
        /// <remarks/>
        public event taobangCompletedEventHandler taobangCompleted;
        
        /// <remarks/>
        public event SinhVien_ThemCompletedEventHandler SinhVien_ThemCompleted;
        
        /// <remarks/>
        public event SinhVien_XoaCompletedEventHandler SinhVien_XoaCompleted;
        
        /// <remarks/>
        public event SinhVien_SuaCompletedEventHandler SinhVien_SuaCompleted;
        
        /// <remarks/>
        public event TaoBangKhoaCompletedEventHandler TaoBangKhoaCompleted;
        
        /// <remarks/>
        public event Khoa_ThemCompletedEventHandler Khoa_ThemCompleted;
        
        /// <remarks/>
        public event Khoa_SuaCompletedEventHandler Khoa_SuaCompleted;
        
        /// <remarks/>
        public event Khoa_XoaCompletedEventHandler Khoa_XoaCompleted;
        
        /// <remarks/>
        public event TaoBangMonHocCompletedEventHandler TaoBangMonHocCompleted;
        
        /// <remarks/>
        public event MonHoc_ThemCompletedEventHandler MonHoc_ThemCompleted;
        
        /// <remarks/>
        public event MonHoc_SuaCompletedEventHandler MonHoc_SuaCompleted;
        
        /// <remarks/>
        public event MonHoc_XoaCompletedEventHandler MonHoc_XoaCompleted;
        
        /// <remarks/>
        public event TaoBangKQCompletedEventHandler TaoBangKQCompleted;
        
        /// <remarks/>
        public event KetQua_ThemCompletedEventHandler KetQua_ThemCompleted;
        
        /// <remarks/>
        public event KetQua_SuaCompletedEventHandler KetQua_SuaCompleted;
        
        /// <remarks/>
        public event KetQua_XoaCompletedEventHandler KetQua_XoaCompleted;
        
        /// <remarks/>
        public event TaoBangTKMonHocCompletedEventHandler TaoBangTKMonHocCompleted;
        
        /// <remarks/>
        public event MONHOC_TimTheoMaMHCompletedEventHandler MONHOC_TimTheoMaMHCompleted;
        
        /// <remarks/>
        public event TaoBangTKKhoaCompletedEventHandler TaoBangTKKhoaCompleted;
        
        /// <remarks/>
        public event Khoa_TimTheoMaKhoaCompletedEventHandler Khoa_TimTheoMaKhoaCompleted;
        
        /// <remarks/>
        public event TaoBangTKLanThiCompletedEventHandler TaoBangTKLanThiCompleted;
        
        /// <remarks/>
        public event KetQua_TimTheoLanThiCompletedEventHandler KetQua_TimTheoLanThiCompleted;
        
        /// <remarks/>
        public event TimKiem_ThongTinSVCompletedEventHandler TimKiem_ThongTinSVCompleted;
        
        /// <remarks/>
        public event TimKiem_ThongTinSVGridViewCompletedEventHandler TimKiem_ThongTinSVGridViewCompleted;
        
        /// <remarks/>
        public event TimKiem_DiemTrungBinhCompletedEventHandler TimKiem_DiemTrungBinhCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/myClose", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void myClose() {
            this.Invoke("myClose", new object[0]);
        }
        
        /// <remarks/>
        public void myCloseAsync() {
            this.myCloseAsync(null);
        }
        
        /// <remarks/>
        public void myCloseAsync(object userState) {
            if ((this.myCloseOperationCompleted == null)) {
                this.myCloseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmyCloseOperationCompleted);
            }
            this.InvokeAsync("myClose", new object[0], this.myCloseOperationCompleted, userState);
        }
        
        private void OnmyCloseOperationCompleted(object arg) {
            if ((this.myCloseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.myCloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/myconnect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void myconnect() {
            this.Invoke("myconnect", new object[0]);
        }
        
        /// <remarks/>
        public void myconnectAsync() {
            this.myconnectAsync(null);
        }
        
        /// <remarks/>
        public void myconnectAsync(object userState) {
            if ((this.myconnectOperationCompleted == null)) {
                this.myconnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmyconnectOperationCompleted);
            }
            this.InvokeAsync("myconnect", new object[0], this.myconnectOperationCompleted, userState);
        }
        
        private void OnmyconnectOperationCompleted(object arg) {
            if ((this.myconnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.myconnectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/taobang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable taobang(string QLSV) {
            object[] results = this.Invoke("taobang", new object[] {
                        QLSV});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void taobangAsync(string QLSV) {
            this.taobangAsync(QLSV, null);
        }
        
        /// <remarks/>
        public void taobangAsync(string QLSV, object userState) {
            if ((this.taobangOperationCompleted == null)) {
                this.taobangOperationCompleted = new System.Threading.SendOrPostCallback(this.OntaobangOperationCompleted);
            }
            this.InvokeAsync("taobang", new object[] {
                        QLSV}, this.taobangOperationCompleted, userState);
        }
        
        private void OntaobangOperationCompleted(object arg) {
            if ((this.taobangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.taobangCompleted(this, new taobangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SinhVien_Them", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SinhVien_Them(string masv, string hosv, string tensv, string gioitinh, System.DateTime ngaysinh, string makhoa) {
            this.Invoke("SinhVien_Them", new object[] {
                        masv,
                        hosv,
                        tensv,
                        gioitinh,
                        ngaysinh,
                        makhoa});
        }
        
        /// <remarks/>
        public void SinhVien_ThemAsync(string masv, string hosv, string tensv, string gioitinh, System.DateTime ngaysinh, string makhoa) {
            this.SinhVien_ThemAsync(masv, hosv, tensv, gioitinh, ngaysinh, makhoa, null);
        }
        
        /// <remarks/>
        public void SinhVien_ThemAsync(string masv, string hosv, string tensv, string gioitinh, System.DateTime ngaysinh, string makhoa, object userState) {
            if ((this.SinhVien_ThemOperationCompleted == null)) {
                this.SinhVien_ThemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSinhVien_ThemOperationCompleted);
            }
            this.InvokeAsync("SinhVien_Them", new object[] {
                        masv,
                        hosv,
                        tensv,
                        gioitinh,
                        ngaysinh,
                        makhoa}, this.SinhVien_ThemOperationCompleted, userState);
        }
        
        private void OnSinhVien_ThemOperationCompleted(object arg) {
            if ((this.SinhVien_ThemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SinhVien_ThemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SinhVien_Xoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SinhVien_Xoa(string masv) {
            this.Invoke("SinhVien_Xoa", new object[] {
                        masv});
        }
        
        /// <remarks/>
        public void SinhVien_XoaAsync(string masv) {
            this.SinhVien_XoaAsync(masv, null);
        }
        
        /// <remarks/>
        public void SinhVien_XoaAsync(string masv, object userState) {
            if ((this.SinhVien_XoaOperationCompleted == null)) {
                this.SinhVien_XoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSinhVien_XoaOperationCompleted);
            }
            this.InvokeAsync("SinhVien_Xoa", new object[] {
                        masv}, this.SinhVien_XoaOperationCompleted, userState);
        }
        
        private void OnSinhVien_XoaOperationCompleted(object arg) {
            if ((this.SinhVien_XoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SinhVien_XoaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SinhVien_Sua", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SinhVien_Sua(string masv, string hosv, string tensv, System.DateTime ngaysinh, string gioitinh, string makhoa) {
            this.Invoke("SinhVien_Sua", new object[] {
                        masv,
                        hosv,
                        tensv,
                        ngaysinh,
                        gioitinh,
                        makhoa});
        }
        
        /// <remarks/>
        public void SinhVien_SuaAsync(string masv, string hosv, string tensv, System.DateTime ngaysinh, string gioitinh, string makhoa) {
            this.SinhVien_SuaAsync(masv, hosv, tensv, ngaysinh, gioitinh, makhoa, null);
        }
        
        /// <remarks/>
        public void SinhVien_SuaAsync(string masv, string hosv, string tensv, System.DateTime ngaysinh, string gioitinh, string makhoa, object userState) {
            if ((this.SinhVien_SuaOperationCompleted == null)) {
                this.SinhVien_SuaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSinhVien_SuaOperationCompleted);
            }
            this.InvokeAsync("SinhVien_Sua", new object[] {
                        masv,
                        hosv,
                        tensv,
                        ngaysinh,
                        gioitinh,
                        makhoa}, this.SinhVien_SuaOperationCompleted, userState);
        }
        
        private void OnSinhVien_SuaOperationCompleted(object arg) {
            if ((this.SinhVien_SuaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SinhVien_SuaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TaoBangKhoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TaoBangKhoa(string QLSV) {
            object[] results = this.Invoke("TaoBangKhoa", new object[] {
                        QLSV});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TaoBangKhoaAsync(string QLSV) {
            this.TaoBangKhoaAsync(QLSV, null);
        }
        
        /// <remarks/>
        public void TaoBangKhoaAsync(string QLSV, object userState) {
            if ((this.TaoBangKhoaOperationCompleted == null)) {
                this.TaoBangKhoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaoBangKhoaOperationCompleted);
            }
            this.InvokeAsync("TaoBangKhoa", new object[] {
                        QLSV}, this.TaoBangKhoaOperationCompleted, userState);
        }
        
        private void OnTaoBangKhoaOperationCompleted(object arg) {
            if ((this.TaoBangKhoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaoBangKhoaCompleted(this, new TaoBangKhoaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Khoa_Them", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Khoa_Them(string makhoa, string tenkhoa) {
            this.Invoke("Khoa_Them", new object[] {
                        makhoa,
                        tenkhoa});
        }
        
        /// <remarks/>
        public void Khoa_ThemAsync(string makhoa, string tenkhoa) {
            this.Khoa_ThemAsync(makhoa, tenkhoa, null);
        }
        
        /// <remarks/>
        public void Khoa_ThemAsync(string makhoa, string tenkhoa, object userState) {
            if ((this.Khoa_ThemOperationCompleted == null)) {
                this.Khoa_ThemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKhoa_ThemOperationCompleted);
            }
            this.InvokeAsync("Khoa_Them", new object[] {
                        makhoa,
                        tenkhoa}, this.Khoa_ThemOperationCompleted, userState);
        }
        
        private void OnKhoa_ThemOperationCompleted(object arg) {
            if ((this.Khoa_ThemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Khoa_ThemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Khoa_Sua", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Khoa_Sua(string makhoa, string tenkhoa) {
            this.Invoke("Khoa_Sua", new object[] {
                        makhoa,
                        tenkhoa});
        }
        
        /// <remarks/>
        public void Khoa_SuaAsync(string makhoa, string tenkhoa) {
            this.Khoa_SuaAsync(makhoa, tenkhoa, null);
        }
        
        /// <remarks/>
        public void Khoa_SuaAsync(string makhoa, string tenkhoa, object userState) {
            if ((this.Khoa_SuaOperationCompleted == null)) {
                this.Khoa_SuaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKhoa_SuaOperationCompleted);
            }
            this.InvokeAsync("Khoa_Sua", new object[] {
                        makhoa,
                        tenkhoa}, this.Khoa_SuaOperationCompleted, userState);
        }
        
        private void OnKhoa_SuaOperationCompleted(object arg) {
            if ((this.Khoa_SuaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Khoa_SuaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Khoa_Xoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Khoa_Xoa(string makhoa) {
            this.Invoke("Khoa_Xoa", new object[] {
                        makhoa});
        }
        
        /// <remarks/>
        public void Khoa_XoaAsync(string makhoa) {
            this.Khoa_XoaAsync(makhoa, null);
        }
        
        /// <remarks/>
        public void Khoa_XoaAsync(string makhoa, object userState) {
            if ((this.Khoa_XoaOperationCompleted == null)) {
                this.Khoa_XoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKhoa_XoaOperationCompleted);
            }
            this.InvokeAsync("Khoa_Xoa", new object[] {
                        makhoa}, this.Khoa_XoaOperationCompleted, userState);
        }
        
        private void OnKhoa_XoaOperationCompleted(object arg) {
            if ((this.Khoa_XoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Khoa_XoaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TaoBangMonHoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TaoBangMonHoc(string QLSV) {
            object[] results = this.Invoke("TaoBangMonHoc", new object[] {
                        QLSV});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TaoBangMonHocAsync(string QLSV) {
            this.TaoBangMonHocAsync(QLSV, null);
        }
        
        /// <remarks/>
        public void TaoBangMonHocAsync(string QLSV, object userState) {
            if ((this.TaoBangMonHocOperationCompleted == null)) {
                this.TaoBangMonHocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaoBangMonHocOperationCompleted);
            }
            this.InvokeAsync("TaoBangMonHoc", new object[] {
                        QLSV}, this.TaoBangMonHocOperationCompleted, userState);
        }
        
        private void OnTaoBangMonHocOperationCompleted(object arg) {
            if ((this.TaoBangMonHocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaoBangMonHocCompleted(this, new TaoBangMonHocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MonHoc_Them", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MonHoc_Them(string mamonhoc, string tenmonhoc, int sotiet) {
            this.Invoke("MonHoc_Them", new object[] {
                        mamonhoc,
                        tenmonhoc,
                        sotiet});
        }
        
        /// <remarks/>
        public void MonHoc_ThemAsync(string mamonhoc, string tenmonhoc, int sotiet) {
            this.MonHoc_ThemAsync(mamonhoc, tenmonhoc, sotiet, null);
        }
        
        /// <remarks/>
        public void MonHoc_ThemAsync(string mamonhoc, string tenmonhoc, int sotiet, object userState) {
            if ((this.MonHoc_ThemOperationCompleted == null)) {
                this.MonHoc_ThemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMonHoc_ThemOperationCompleted);
            }
            this.InvokeAsync("MonHoc_Them", new object[] {
                        mamonhoc,
                        tenmonhoc,
                        sotiet}, this.MonHoc_ThemOperationCompleted, userState);
        }
        
        private void OnMonHoc_ThemOperationCompleted(object arg) {
            if ((this.MonHoc_ThemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MonHoc_ThemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MonHoc_Sua", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MonHoc_Sua(string mamonhoc, string tenmonhoc, int sotiet) {
            this.Invoke("MonHoc_Sua", new object[] {
                        mamonhoc,
                        tenmonhoc,
                        sotiet});
        }
        
        /// <remarks/>
        public void MonHoc_SuaAsync(string mamonhoc, string tenmonhoc, int sotiet) {
            this.MonHoc_SuaAsync(mamonhoc, tenmonhoc, sotiet, null);
        }
        
        /// <remarks/>
        public void MonHoc_SuaAsync(string mamonhoc, string tenmonhoc, int sotiet, object userState) {
            if ((this.MonHoc_SuaOperationCompleted == null)) {
                this.MonHoc_SuaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMonHoc_SuaOperationCompleted);
            }
            this.InvokeAsync("MonHoc_Sua", new object[] {
                        mamonhoc,
                        tenmonhoc,
                        sotiet}, this.MonHoc_SuaOperationCompleted, userState);
        }
        
        private void OnMonHoc_SuaOperationCompleted(object arg) {
            if ((this.MonHoc_SuaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MonHoc_SuaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MonHoc_Xoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MonHoc_Xoa(string mamonhoc) {
            this.Invoke("MonHoc_Xoa", new object[] {
                        mamonhoc});
        }
        
        /// <remarks/>
        public void MonHoc_XoaAsync(string mamonhoc) {
            this.MonHoc_XoaAsync(mamonhoc, null);
        }
        
        /// <remarks/>
        public void MonHoc_XoaAsync(string mamonhoc, object userState) {
            if ((this.MonHoc_XoaOperationCompleted == null)) {
                this.MonHoc_XoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMonHoc_XoaOperationCompleted);
            }
            this.InvokeAsync("MonHoc_Xoa", new object[] {
                        mamonhoc}, this.MonHoc_XoaOperationCompleted, userState);
        }
        
        private void OnMonHoc_XoaOperationCompleted(object arg) {
            if ((this.MonHoc_XoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MonHoc_XoaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TaoBangKQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TaoBangKQ(string QLSV) {
            object[] results = this.Invoke("TaoBangKQ", new object[] {
                        QLSV});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TaoBangKQAsync(string QLSV) {
            this.TaoBangKQAsync(QLSV, null);
        }
        
        /// <remarks/>
        public void TaoBangKQAsync(string QLSV, object userState) {
            if ((this.TaoBangKQOperationCompleted == null)) {
                this.TaoBangKQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaoBangKQOperationCompleted);
            }
            this.InvokeAsync("TaoBangKQ", new object[] {
                        QLSV}, this.TaoBangKQOperationCompleted, userState);
        }
        
        private void OnTaoBangKQOperationCompleted(object arg) {
            if ((this.TaoBangKQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaoBangKQCompleted(this, new TaoBangKQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KetQua_Them", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KetQua_Them(string masinhvien, string mamonhoc, int lanthi, int diem) {
            this.Invoke("KetQua_Them", new object[] {
                        masinhvien,
                        mamonhoc,
                        lanthi,
                        diem});
        }
        
        /// <remarks/>
        public void KetQua_ThemAsync(string masinhvien, string mamonhoc, int lanthi, int diem) {
            this.KetQua_ThemAsync(masinhvien, mamonhoc, lanthi, diem, null);
        }
        
        /// <remarks/>
        public void KetQua_ThemAsync(string masinhvien, string mamonhoc, int lanthi, int diem, object userState) {
            if ((this.KetQua_ThemOperationCompleted == null)) {
                this.KetQua_ThemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKetQua_ThemOperationCompleted);
            }
            this.InvokeAsync("KetQua_Them", new object[] {
                        masinhvien,
                        mamonhoc,
                        lanthi,
                        diem}, this.KetQua_ThemOperationCompleted, userState);
        }
        
        private void OnKetQua_ThemOperationCompleted(object arg) {
            if ((this.KetQua_ThemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KetQua_ThemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KetQua_Sua", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KetQua_Sua(string masinhvien, string mamonhoc, int lanthi, int diem) {
            this.Invoke("KetQua_Sua", new object[] {
                        masinhvien,
                        mamonhoc,
                        lanthi,
                        diem});
        }
        
        /// <remarks/>
        public void KetQua_SuaAsync(string masinhvien, string mamonhoc, int lanthi, int diem) {
            this.KetQua_SuaAsync(masinhvien, mamonhoc, lanthi, diem, null);
        }
        
        /// <remarks/>
        public void KetQua_SuaAsync(string masinhvien, string mamonhoc, int lanthi, int diem, object userState) {
            if ((this.KetQua_SuaOperationCompleted == null)) {
                this.KetQua_SuaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKetQua_SuaOperationCompleted);
            }
            this.InvokeAsync("KetQua_Sua", new object[] {
                        masinhvien,
                        mamonhoc,
                        lanthi,
                        diem}, this.KetQua_SuaOperationCompleted, userState);
        }
        
        private void OnKetQua_SuaOperationCompleted(object arg) {
            if ((this.KetQua_SuaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KetQua_SuaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KetQua_Xoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KetQua_Xoa(string masinhvien) {
            this.Invoke("KetQua_Xoa", new object[] {
                        masinhvien});
        }
        
        /// <remarks/>
        public void KetQua_XoaAsync(string masinhvien) {
            this.KetQua_XoaAsync(masinhvien, null);
        }
        
        /// <remarks/>
        public void KetQua_XoaAsync(string masinhvien, object userState) {
            if ((this.KetQua_XoaOperationCompleted == null)) {
                this.KetQua_XoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKetQua_XoaOperationCompleted);
            }
            this.InvokeAsync("KetQua_Xoa", new object[] {
                        masinhvien}, this.KetQua_XoaOperationCompleted, userState);
        }
        
        private void OnKetQua_XoaOperationCompleted(object arg) {
            if ((this.KetQua_XoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KetQua_XoaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TaoBangTKMonHoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TaoBangTKMonHoc(string mamonhoc) {
            object[] results = this.Invoke("TaoBangTKMonHoc", new object[] {
                        mamonhoc});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TaoBangTKMonHocAsync(string mamonhoc) {
            this.TaoBangTKMonHocAsync(mamonhoc, null);
        }
        
        /// <remarks/>
        public void TaoBangTKMonHocAsync(string mamonhoc, object userState) {
            if ((this.TaoBangTKMonHocOperationCompleted == null)) {
                this.TaoBangTKMonHocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaoBangTKMonHocOperationCompleted);
            }
            this.InvokeAsync("TaoBangTKMonHoc", new object[] {
                        mamonhoc}, this.TaoBangTKMonHocOperationCompleted, userState);
        }
        
        private void OnTaoBangTKMonHocOperationCompleted(object arg) {
            if ((this.TaoBangTKMonHocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaoBangTKMonHocCompleted(this, new TaoBangTKMonHocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MONHOC_TimTheoMaMH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MONHOC_TimTheoMaMH(string mamonhoc) {
            object[] results = this.Invoke("MONHOC_TimTheoMaMH", new object[] {
                        mamonhoc});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MONHOC_TimTheoMaMHAsync(string mamonhoc) {
            this.MONHOC_TimTheoMaMHAsync(mamonhoc, null);
        }
        
        /// <remarks/>
        public void MONHOC_TimTheoMaMHAsync(string mamonhoc, object userState) {
            if ((this.MONHOC_TimTheoMaMHOperationCompleted == null)) {
                this.MONHOC_TimTheoMaMHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMONHOC_TimTheoMaMHOperationCompleted);
            }
            this.InvokeAsync("MONHOC_TimTheoMaMH", new object[] {
                        mamonhoc}, this.MONHOC_TimTheoMaMHOperationCompleted, userState);
        }
        
        private void OnMONHOC_TimTheoMaMHOperationCompleted(object arg) {
            if ((this.MONHOC_TimTheoMaMHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MONHOC_TimTheoMaMHCompleted(this, new MONHOC_TimTheoMaMHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TaoBangTKKhoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TaoBangTKKhoa(string makhoa) {
            object[] results = this.Invoke("TaoBangTKKhoa", new object[] {
                        makhoa});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TaoBangTKKhoaAsync(string makhoa) {
            this.TaoBangTKKhoaAsync(makhoa, null);
        }
        
        /// <remarks/>
        public void TaoBangTKKhoaAsync(string makhoa, object userState) {
            if ((this.TaoBangTKKhoaOperationCompleted == null)) {
                this.TaoBangTKKhoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaoBangTKKhoaOperationCompleted);
            }
            this.InvokeAsync("TaoBangTKKhoa", new object[] {
                        makhoa}, this.TaoBangTKKhoaOperationCompleted, userState);
        }
        
        private void OnTaoBangTKKhoaOperationCompleted(object arg) {
            if ((this.TaoBangTKKhoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaoBangTKKhoaCompleted(this, new TaoBangTKKhoaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Khoa_TimTheoMaKhoa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Khoa_TimTheoMaKhoa(string makhoa) {
            object[] results = this.Invoke("Khoa_TimTheoMaKhoa", new object[] {
                        makhoa});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Khoa_TimTheoMaKhoaAsync(string makhoa) {
            this.Khoa_TimTheoMaKhoaAsync(makhoa, null);
        }
        
        /// <remarks/>
        public void Khoa_TimTheoMaKhoaAsync(string makhoa, object userState) {
            if ((this.Khoa_TimTheoMaKhoaOperationCompleted == null)) {
                this.Khoa_TimTheoMaKhoaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKhoa_TimTheoMaKhoaOperationCompleted);
            }
            this.InvokeAsync("Khoa_TimTheoMaKhoa", new object[] {
                        makhoa}, this.Khoa_TimTheoMaKhoaOperationCompleted, userState);
        }
        
        private void OnKhoa_TimTheoMaKhoaOperationCompleted(object arg) {
            if ((this.Khoa_TimTheoMaKhoaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Khoa_TimTheoMaKhoaCompleted(this, new Khoa_TimTheoMaKhoaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TaoBangTKLanThi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TaoBangTKLanThi(string lanthi) {
            object[] results = this.Invoke("TaoBangTKLanThi", new object[] {
                        lanthi});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TaoBangTKLanThiAsync(string lanthi) {
            this.TaoBangTKLanThiAsync(lanthi, null);
        }
        
        /// <remarks/>
        public void TaoBangTKLanThiAsync(string lanthi, object userState) {
            if ((this.TaoBangTKLanThiOperationCompleted == null)) {
                this.TaoBangTKLanThiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaoBangTKLanThiOperationCompleted);
            }
            this.InvokeAsync("TaoBangTKLanThi", new object[] {
                        lanthi}, this.TaoBangTKLanThiOperationCompleted, userState);
        }
        
        private void OnTaoBangTKLanThiOperationCompleted(object arg) {
            if ((this.TaoBangTKLanThiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaoBangTKLanThiCompleted(this, new TaoBangTKLanThiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KetQua_TimTheoLanThi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable KetQua_TimTheoLanThi(string lanthi) {
            object[] results = this.Invoke("KetQua_TimTheoLanThi", new object[] {
                        lanthi});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void KetQua_TimTheoLanThiAsync(string lanthi) {
            this.KetQua_TimTheoLanThiAsync(lanthi, null);
        }
        
        /// <remarks/>
        public void KetQua_TimTheoLanThiAsync(string lanthi, object userState) {
            if ((this.KetQua_TimTheoLanThiOperationCompleted == null)) {
                this.KetQua_TimTheoLanThiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKetQua_TimTheoLanThiOperationCompleted);
            }
            this.InvokeAsync("KetQua_TimTheoLanThi", new object[] {
                        lanthi}, this.KetQua_TimTheoLanThiOperationCompleted, userState);
        }
        
        private void OnKetQua_TimTheoLanThiOperationCompleted(object arg) {
            if ((this.KetQua_TimTheoLanThiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KetQua_TimTheoLanThiCompleted(this, new KetQua_TimTheoLanThiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimKiem_ThongTinSV", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TimKiem_ThongTinSV(string masinhvien) {
            object[] results = this.Invoke("TimKiem_ThongTinSV", new object[] {
                        masinhvien});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TimKiem_ThongTinSVAsync(string masinhvien) {
            this.TimKiem_ThongTinSVAsync(masinhvien, null);
        }
        
        /// <remarks/>
        public void TimKiem_ThongTinSVAsync(string masinhvien, object userState) {
            if ((this.TimKiem_ThongTinSVOperationCompleted == null)) {
                this.TimKiem_ThongTinSVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimKiem_ThongTinSVOperationCompleted);
            }
            this.InvokeAsync("TimKiem_ThongTinSV", new object[] {
                        masinhvien}, this.TimKiem_ThongTinSVOperationCompleted, userState);
        }
        
        private void OnTimKiem_ThongTinSVOperationCompleted(object arg) {
            if ((this.TimKiem_ThongTinSVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimKiem_ThongTinSVCompleted(this, new TimKiem_ThongTinSVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimKiem_ThongTinSVGridView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TimKiem_ThongTinSVGridView(string masinhvien) {
            object[] results = this.Invoke("TimKiem_ThongTinSVGridView", new object[] {
                        masinhvien});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TimKiem_ThongTinSVGridViewAsync(string masinhvien) {
            this.TimKiem_ThongTinSVGridViewAsync(masinhvien, null);
        }
        
        /// <remarks/>
        public void TimKiem_ThongTinSVGridViewAsync(string masinhvien, object userState) {
            if ((this.TimKiem_ThongTinSVGridViewOperationCompleted == null)) {
                this.TimKiem_ThongTinSVGridViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimKiem_ThongTinSVGridViewOperationCompleted);
            }
            this.InvokeAsync("TimKiem_ThongTinSVGridView", new object[] {
                        masinhvien}, this.TimKiem_ThongTinSVGridViewOperationCompleted, userState);
        }
        
        private void OnTimKiem_ThongTinSVGridViewOperationCompleted(object arg) {
            if ((this.TimKiem_ThongTinSVGridViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimKiem_ThongTinSVGridViewCompleted(this, new TimKiem_ThongTinSVGridViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimKiem_DiemTrungBinh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TimKiem_DiemTrungBinh(string masinhvien) {
            object[] results = this.Invoke("TimKiem_DiemTrungBinh", new object[] {
                        masinhvien});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TimKiem_DiemTrungBinhAsync(string masinhvien) {
            this.TimKiem_DiemTrungBinhAsync(masinhvien, null);
        }
        
        /// <remarks/>
        public void TimKiem_DiemTrungBinhAsync(string masinhvien, object userState) {
            if ((this.TimKiem_DiemTrungBinhOperationCompleted == null)) {
                this.TimKiem_DiemTrungBinhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimKiem_DiemTrungBinhOperationCompleted);
            }
            this.InvokeAsync("TimKiem_DiemTrungBinh", new object[] {
                        masinhvien}, this.TimKiem_DiemTrungBinhOperationCompleted, userState);
        }
        
        private void OnTimKiem_DiemTrungBinhOperationCompleted(object arg) {
            if ((this.TimKiem_DiemTrungBinhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimKiem_DiemTrungBinhCompleted(this, new TimKiem_DiemTrungBinhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void myCloseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void myconnectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void taobangCompletedEventHandler(object sender, taobangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class taobangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal taobangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SinhVien_ThemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SinhVien_XoaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SinhVien_SuaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TaoBangKhoaCompletedEventHandler(object sender, TaoBangKhoaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaoBangKhoaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TaoBangKhoaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Khoa_ThemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Khoa_SuaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Khoa_XoaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TaoBangMonHocCompletedEventHandler(object sender, TaoBangMonHocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaoBangMonHocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TaoBangMonHocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MonHoc_ThemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MonHoc_SuaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MonHoc_XoaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TaoBangKQCompletedEventHandler(object sender, TaoBangKQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaoBangKQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TaoBangKQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KetQua_ThemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KetQua_SuaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KetQua_XoaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TaoBangTKMonHocCompletedEventHandler(object sender, TaoBangTKMonHocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaoBangTKMonHocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TaoBangTKMonHocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void MONHOC_TimTheoMaMHCompletedEventHandler(object sender, MONHOC_TimTheoMaMHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MONHOC_TimTheoMaMHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MONHOC_TimTheoMaMHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TaoBangTKKhoaCompletedEventHandler(object sender, TaoBangTKKhoaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaoBangTKKhoaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TaoBangTKKhoaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Khoa_TimTheoMaKhoaCompletedEventHandler(object sender, Khoa_TimTheoMaKhoaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Khoa_TimTheoMaKhoaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Khoa_TimTheoMaKhoaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TaoBangTKLanThiCompletedEventHandler(object sender, TaoBangTKLanThiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaoBangTKLanThiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TaoBangTKLanThiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KetQua_TimTheoLanThiCompletedEventHandler(object sender, KetQua_TimTheoLanThiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KetQua_TimTheoLanThiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KetQua_TimTheoLanThiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TimKiem_ThongTinSVCompletedEventHandler(object sender, TimKiem_ThongTinSVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimKiem_ThongTinSVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimKiem_ThongTinSVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TimKiem_ThongTinSVGridViewCompletedEventHandler(object sender, TimKiem_ThongTinSVGridViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimKiem_ThongTinSVGridViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimKiem_ThongTinSVGridViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TimKiem_DiemTrungBinhCompletedEventHandler(object sender, TimKiem_DiemTrungBinhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimKiem_DiemTrungBinhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimKiem_DiemTrungBinhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591