//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySinhVien.QLSinhVien {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QLSinhVien.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myClose", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void myClose();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/myconnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void myconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/taobang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable taobang(string QLSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SinhVien_Them", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SinhVien_Them(string masv, string hosv, string tensv, string gioitinh, System.DateTime ngaysinh, string makhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SinhVien_Xoa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SinhVien_Xoa(string masv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SinhVien_Sua", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SinhVien_Sua(string masv, string hosv, string tensv, System.DateTime ngaysinh, string gioitinh, string makhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoBangKhoa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TaoBangKhoa(string QLSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Khoa_Them", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Khoa_Them(string makhoa, string tenkhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Khoa_Sua", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Khoa_Sua(string makhoa, string tenkhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Khoa_Xoa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Khoa_Xoa(string makhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoBangMonHoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TaoBangMonHoc(string QLSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_Them", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void MonHoc_Them(string mamonhoc, string tenmonhoc, int sotiet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_Sua", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void MonHoc_Sua(string mamonhoc, string tenmonhoc, int sotiet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MonHoc_Xoa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void MonHoc_Xoa(string mamonhoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoBangKQ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TaoBangKQ(string QLSV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KetQua_Them", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void KetQua_Them(string masinhvien, string mamonhoc, int lanthi, int diem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KetQua_Sua", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void KetQua_Sua(string masinhvien, string mamonhoc, int lanthi, int diem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KetQua_Xoa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void KetQua_Xoa(string masinhvien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoBangTKMonHoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TaoBangTKMonHoc(string mamonhoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MONHOC_TimTheoMaMH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MONHOC_TimTheoMaMH(string mamonhoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoBangTKKhoa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TaoBangTKKhoa(string makhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Khoa_TimTheoMaKhoa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Khoa_TimTheoMaKhoa(string makhoa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoBangTKLanThi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TaoBangTKLanThi(string lanthi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KetQua_TimTheoLanThi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable KetQua_TimTheoLanThi(string lanthi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiem_ThongTinSV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiem_ThongTinSV(string masinhvien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiem_ThongTinSVGridView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiem_ThongTinSVGridView(string masinhvien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimKiem_DiemTrungBinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TimKiem_DiemTrungBinh(string masinhvien);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : QuanLySinhVien.QLSinhVien.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<QuanLySinhVien.QLSinhVien.Service1Soap>, QuanLySinhVien.QLSinhVien.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void myClose() {
            base.Channel.myClose();
        }
        
        public void myconnect() {
            base.Channel.myconnect();
        }
        
        public System.Data.DataTable taobang(string QLSV) {
            return base.Channel.taobang(QLSV);
        }
        
        public void SinhVien_Them(string masv, string hosv, string tensv, string gioitinh, System.DateTime ngaysinh, string makhoa) {
            base.Channel.SinhVien_Them(masv, hosv, tensv, gioitinh, ngaysinh, makhoa);
        }
        
        public void SinhVien_Xoa(string masv) {
            base.Channel.SinhVien_Xoa(masv);
        }
        
        public void SinhVien_Sua(string masv, string hosv, string tensv, System.DateTime ngaysinh, string gioitinh, string makhoa) {
            base.Channel.SinhVien_Sua(masv, hosv, tensv, ngaysinh, gioitinh, makhoa);
        }
        
        public System.Data.DataTable TaoBangKhoa(string QLSV) {
            return base.Channel.TaoBangKhoa(QLSV);
        }
        
        public void Khoa_Them(string makhoa, string tenkhoa) {
            base.Channel.Khoa_Them(makhoa, tenkhoa);
        }
        
        public void Khoa_Sua(string makhoa, string tenkhoa) {
            base.Channel.Khoa_Sua(makhoa, tenkhoa);
        }
        
        public void Khoa_Xoa(string makhoa) {
            base.Channel.Khoa_Xoa(makhoa);
        }
        
        public System.Data.DataTable TaoBangMonHoc(string QLSV) {
            return base.Channel.TaoBangMonHoc(QLSV);
        }
        
        public void MonHoc_Them(string mamonhoc, string tenmonhoc, int sotiet) {
            base.Channel.MonHoc_Them(mamonhoc, tenmonhoc, sotiet);
        }
        
        public void MonHoc_Sua(string mamonhoc, string tenmonhoc, int sotiet) {
            base.Channel.MonHoc_Sua(mamonhoc, tenmonhoc, sotiet);
        }
        
        public void MonHoc_Xoa(string mamonhoc) {
            base.Channel.MonHoc_Xoa(mamonhoc);
        }
        
        public System.Data.DataTable TaoBangKQ(string QLSV) {
            return base.Channel.TaoBangKQ(QLSV);
        }
        
        public void KetQua_Them(string masinhvien, string mamonhoc, int lanthi, int diem) {
            base.Channel.KetQua_Them(masinhvien, mamonhoc, lanthi, diem);
        }
        
        public void KetQua_Sua(string masinhvien, string mamonhoc, int lanthi, int diem) {
            base.Channel.KetQua_Sua(masinhvien, mamonhoc, lanthi, diem);
        }
        
        public void KetQua_Xoa(string masinhvien) {
            base.Channel.KetQua_Xoa(masinhvien);
        }
        
        public System.Data.DataTable TaoBangTKMonHoc(string mamonhoc) {
            return base.Channel.TaoBangTKMonHoc(mamonhoc);
        }
        
        public System.Data.DataTable MONHOC_TimTheoMaMH(string mamonhoc) {
            return base.Channel.MONHOC_TimTheoMaMH(mamonhoc);
        }
        
        public System.Data.DataTable TaoBangTKKhoa(string makhoa) {
            return base.Channel.TaoBangTKKhoa(makhoa);
        }
        
        public System.Data.DataTable Khoa_TimTheoMaKhoa(string makhoa) {
            return base.Channel.Khoa_TimTheoMaKhoa(makhoa);
        }
        
        public System.Data.DataTable TaoBangTKLanThi(string lanthi) {
            return base.Channel.TaoBangTKLanThi(lanthi);
        }
        
        public System.Data.DataTable KetQua_TimTheoLanThi(string lanthi) {
            return base.Channel.KetQua_TimTheoLanThi(lanthi);
        }
        
        public System.Data.DataTable TimKiem_ThongTinSV(string masinhvien) {
            return base.Channel.TimKiem_ThongTinSV(masinhvien);
        }
        
        public System.Data.DataTable TimKiem_ThongTinSVGridView(string masinhvien) {
            return base.Channel.TimKiem_ThongTinSVGridView(masinhvien);
        }
        
        public System.Data.DataTable TimKiem_DiemTrungBinh(string masinhvien) {
            return base.Channel.TimKiem_DiemTrungBinh(masinhvien);
        }
    }
}
